mirror:
  stage: deploy
  tags:
    - docker
  script:
    - git clone --bare https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/filiosoft-oss/filiosoft.net.git
    - cd filiosoft.net.git
    - git push --mirror https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/filiosoft.github.io.git
pages:
  stage: deploy
  image: filiosoft/rsync:latest
  tags:
    - docker
  script:
  - mkdir public
  - rsync -r --exclude=public * public
  artifacts:
    paths:
    - public