mirror:
  stage: deploy
  tags:
    - docker
  script:
    - git clone --bare https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/filiosoft-osp/filiosoft.net.git
    - cd filiosoft.net.git
    - git push --mirror https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/filiosoft.github.io.git