mirror:
  stage: deploy
  tags:
    - docker
  script:
    - git clone --bare https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/oss/oss.filiosoft.net.git
    - cd oss.filiosoft.net.git
    - git push --mirror https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/filiosoft.github.io.git
pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  image: node:6
  tags:
    - docker
  before_script:
  - npm install -qq -g gulp-cli
  - npm install -qq
  script:
  - gulp all
  - rm -r node_modules/
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master